keywords:
  "coop|migros": 4050
  "SBB Bahnhof": 6640
  "salt": 6510
  "Salt Mobile SA": 6510
  "Burkhart & Partners AG": 6530
  "Swisscom": 6510
  "Salär": 2850
  "BANK-now AG": 6260
  "Parkgebühr": 6020
  "BP Tankstelle": 6210
  "Amici miei": 6641
  "Bancomat Bezug": 2850
  "TAVERNE LAUFENBACH": 6641
  "AVIA Tankstelle": 6210
  "Parkhaus": 6020
  "Miete": 6000
  "Helvetia Schweizerische Lebensversicherungsgesellschaft": 5720
  "Spar": 2850
  "Karim's Weinbistro": 6641
  "fifo": 6641
  "Abschlussbetreffnis": 6940
  "Gebühr Zahlungsverkehr": 6940
  "Gebührenbelastung Kartentransaktionen": 6940
  "Gebührenbelastung Kontoführung": 6940
  "Top Shop": 6641
  "SV (Schweiz)": 2850
  "AXA Versicherungen": 6300
  "CembraPay AG": 6640
  "Berti Druck AG": 6500
  "Vistaprint": 6500
  "PaperLand": 6500
  "Eni Wetzikon": 6210
  "SVA ZÜRICH": 5700
  "RADISSON BLU ZURICH": 6641
  "Hotel Schweizerhof": 6641
  "Restaurant Kronenhal": 6641
  "Nebenkosten": 6000
  "SWISS INTER.AIRLINES": 6641
  "global sana": 3401
  "avec": 5820
  "Pizzeria Roma": 6641
  "Strassenverkehrsamt": 6220
  "Denner": 6641
  "Digitec Galaxus": 3402
  
  
  



  


  "Maucieri": 3402
  "Pascal Sigrist": 3402
  "Jeremy Marc Bovens": 3402
  "Piero Laportosa": 3402
  "GIUSEPPE MILANO": 3402
  "Vincenzo G. Randone": 3402

  "ASATE AG": 3402
  "Christophe Schärer": 3402
  "Boris Jung": 3402
  "Monika Müntener": 3402
  "PASCAL SCHULER": 3402
  "Luca La Ferlita": 3402
  "Luca Foresto": 3402
  "MARCO TRAVERSO": 3402
  "Luciano Salzano": 3402
  

  

  "Luigi Drago": 3400

  "Howden Broker Service": 3401 
  "BSC Broker Service Center GmbH": 3401 
