keywords:
  "coop|migros": 4050
  "sbb": 6850
  "salt": 6510
  "Salt Mobile SA": 6510
  "Burkhart & Partners AG": 6530
  "Swisscom": 6510
  "Salär": 2850
  "BANK-now AG": 6260
  "Parkgebühr": 6020
  "BP Tankstelle": 6210
  "Amici miei": 6641
  "Bancomat Bezug": 2850
  "TAVERNE LAUFENBACH": 6641
  "AVIA Tankstelle": 6210
  "Parkhaus": 6020
  "Miete": 6000
  "Helvetia Schweizerische Lebensversicherungsgesellschaft": 5720
