keywords:
  "coop|migros": 4050
  "SBB Bahnhof": 6640
  "salt": 6510
  "Salt Mobile SA": 6510
  "Burkhart & Partners AG": 6530
  "Swisscom": 6510
  "Salär": 2850
  "BANK-now AG": 6260
  "Parkgebühr": 6020
  "BP Tankstelle": 6210
  "Amici miei": 6641
  "Bancomat Bezug": 2850
  "TAVERNE LAUFENBACH": 6641
  "AVIA Tankstelle": 6210
  "Parkhaus": 6020
  "Miete": 6000
  "Helvetia Schweizerische Lebensversicherungsgesellschaft": 5720
  "Spar": 2850
  "Karim's Weinbistro": 6641
  "fifo": 6641
  "Abschlussbetreffnis": 6940
  "Gebühr Zahlungsverkehr": 6940
  "Gebührenbelastung Kartentransaktionen": 6940
  "Gebührenbelastung Kontoführung": 6940
  "Top Shop": 6641
  "SV (Schweiz)": 2850
  "AXA Versicherungen": 6300
  "CembraPay AG": 6640
  "Berti Druck AG": 6500
  "PaperLand": 6500
  "Eni Wetzikon": 6210


  


  "Maucieri": 3402
  "Zahlung Pascal Sigrist": 3402
  "Jeremy Marc Bovens": 3402
  "Piero Laportosa": 3402

  "Luigi Drago": 3400

  "Howden Broker Service": 3401 
  "BSC Broker Service Center GmbH": 3401 
