name: Build & Deploy stlite
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write   # mandatory for deploy-pages@v4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @stlite/browser      # installs stlite toolchain
      - run: stlite dump app.py --requirements requirements.txt
      - uses: actions/upload-pages-artifact@v3
        with: {path: dist}                      # stlite creates ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: {name: github-pages}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
